authenticationclasses: com.bill.security.authentication.MySQLAuthenticate,com.bill.security.authentication.GoogleAuthenticate,com.bill.security.authentication.FacebookAuthenticate
authenticationurls: /login/mySQL,/register,/login/google,/login/facebook
dbURL: jdbc:mysql://hubidb.ckanvfhiy4r6.us-east-2.rds.amazonaws.com:3306/hubi
dbUser: admin
dbPassword: Gu0s0ng_who_$

googleId: 316649002787-pj5ruij4ppogj900cppl4sjjn4ov06c2.apps.googleusercontent.com/multi-channel-auth
googleSecret: zKr-gkjsVnxut-zTZoSxO0aN
facebookId: 151036816561758
facebookSecret: 51e9973ddef335ace3d039015fac0f4f

spring:
    datasource:
        url: jdbc:mysql://hubidb.ckanvfhiy4r6.us-east-2.rds.amazonaws.com:3306/hubi
        username: admin
        password: Gu0s0ng_who_$

    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                format-sql: true
    security:
      oauth2:
        client:
          registration:
            google:
              clientId: 316649002787-pj5ruij4ppogj900cppl4sjjn4ov06c2.apps.googleusercontent.com
              clientSecret: zKr-gkjsVnxut-zTZoSxO0aN
              scope:
              - email
              - profile
            facebook:
              clientId: 151036816561758
              clientSecret: 51e9973ddef335ace3d039015fac0f4f
              scope:
              - email
              - public_profile